# Job Application Agent Configuration
# Copy this file and customize with your credentials

# Platform Credentials
credentials:
  linkedin:
    email: "ddanielh5@gmail.com"
    password: "2513fuhe"
  
  wellfound:
    email: "danielhe.danielhe@gmail.com" 
    password: "dVF3(32ct"
  
  # Email account for Greenhouse verification
  verification_email:
    address: "danielhe.danielhe@gmail.com"
    password: "ncle swmi olxw sbvr"  # Gmail App Password, not regular password
    imap_server: "imap.gmail.com"
    imap_port: 993

# Proxy Configuration (optional)
proxy:
  enabled: false
  # Uncomment and configure if using proxy service
  # host: "rotating-residential.brightdata.com"
  # port: 22225
  # username: "your_proxy_username"
  # password: "your_proxy_password"

# Job Search Configuration
search_settings:
  # Default search criteria
  default_keywords:
    - "Solutions Engineer"
    - "Financial Analyst"
    - "Analyst"
    - "Forward Deployed Engineer"
    - "Deployment Strategist"
    - "Corporate Finance"
    - "Business Development"
  
  default_locations:
    - "San Francisco Bay Area"
    - "New York City"
    - "Chicago"
    - "Atlanta"
  
  # Job filtering
  experience_levels:
    - "Entry level"
    - "Internship"
  
  date_posted: "Past week"  # Past 24 hours, Past week, Past month
  easy_apply_only: true
  remote_options: "Remote"  # On-site, Remote, Hybrid

# Application Settings
application:
  max_applications_per_session: 100
  max_applications_per_platform: 100
  delay_between_applications: 30  # seconds
  
  # Resume and cover letter paths
  resume_path: "./documents/resume.pdf"
  cover_letter_template: "./documents/cover_letter_template.txt"
  
  # Default application answers
  # Personal information for application forms
  personal_info:
    first_name: "Daniel"
    last_name: "He"
    phone_number: "6505808088"
  
  default_answers:
    years_experience: "0-1 years"
    willing_to_relocate: true
    authorized_to_work: true
    require_sponsorship: false
    salary_expectation: "Competitive"
    availability: "Immediately available"

# State Management
state:
  storage_type: "sqlite"  # sqlite or csv
  database_path: "./data/job_applications.db"
  
# Browser Settings
browser:
  headless: false  # Non-headless for better stealth
  stealth_mode: true  # Enable playwright-stealth
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  window_size:
    width: 1440
    height: 900
  # Anti-fingerprinting settings
  locale: "en-US"
  timezone: "America/New_York"
  device_memory: 8
  cpu_cores: 4
  randomize_viewport: true
  
# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "./logs/job_agent.log"
  max_log_size_mb: 10
  backup_count: 5

# Platform-specific Settings
platforms:
  linkedin:
    enabled: true
    search_url: "https://www.linkedin.com/jobs/search/"
    easy_apply_filter: true
    
  wellfound:
    enabled: true
    search_url: "https://wellfound.com/jobs"
    
  # Add more platforms as needed
  # indeed:
  #   enabled: false
  #   search_url: "https://www.indeed.com/jobs"

# Google Sheets Reporting (optional)
google_sheets:
  enabled: true  # Re-enabled after adding test user
  spreadsheet_id: "1nY5Q6_JroKLly_OBA8FRYUSzR1rzGXX8u5XupbR-oTI"  # Get from Google Sheets URL
  sheet_name: "Sheet1"  # Use the default sheet name
  credentials_path: "google_credentials.json"  # Path to Google API credentials