ai:
  relevance_threshold: 6
application:
  cover_letter_template: ./documents/cover_letter_template.txt
  default_answers:
    authorized_to_work: true
    availability: Immediately available
    require_sponsorship: false
    salary_expectation: Competitive
    willing_to_relocate: true
    years_experience: 0-1 years
  delay_between_applications: 30
  max_applications_per_platform: 100
  max_applications_per_session: 100
  personal_info:
    first_name: Daniel
    last_name: He
    phone_number: '6505808088'
  resume_path: /home/daniel/JobApp/documents/resume.pdf
browser:
  cpu_cores: 4
  device_memory: 8
  extra_delays:
    between_actions: 5000
    page_load: 10000
    session_delay: 30000
    typing_delay: 300
  headless: false
  locale: en-US
  random_mouse_movements: true
  random_scrolling: true
  randomize_viewport: true
  stealth_mode: true
  timezone: America/New_York
  typing_errors: true
  user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/120.0.0.0 Safari/537.36
  window_size:
    height: 900
    width: 1440
captcha_solver:
  api_key: your_2captcha_api_key_here
  enabled: false
  retry_attempts: 3
  service: 2captcha
  settings:
    hcaptcha_timeout: 60
    language: en
    min_score: 0.3
    polling_interval: 5
    recaptcha_timeout: 60
  timeout: 120
credentials:
  linkedin:
    email: ddanielh5@gmail.com
    password: 2513fuhe
  verification_email:
    address: danielhe.danielhe@gmail.com
    imap_port: 993
    imap_server: imap.gmail.com
    password: ncle swmi olxw sbvr
  wellfound:
    email: danielhe.danielhe@gmail.com
    password: dVF3(32ct
gemini:
  api_key: ${GOOGLE_API_KEY}  # Set via environment variable
google_sheets:
  credentials_path: google_credentials.json
  enabled: true
  sheet_name: Sheet1
  spreadsheet_id: 1nY5Q6_JroKLly_OBA8FRYUSzR1rzGXX8u5XupbR-oTI
logging:
  backup_count: 5
  level: INFO
  log_file: ./logs/job_agent.log
  max_log_size_mb: 10
platforms:
  linkedin:
    easy_apply_filter: true
    enabled: true
    search_url: https://www.linkedin.com/jobs/search/
  wellfound:
    enabled: true
    search_url: https://wellfound.com/jobs
prompts:
  generate_cover_letter: 'Generate a professional, 3-paragraph cover letter (300-400
    words) for the following role, tailored to the company and highlighting the candidate''s
    relevant skills. Job Posting: [JOB_DESCRIPTION]. User Profile: [USER_PROFILE]'
  optimize_resume_keywords: 'Optimize the following resume section to better match
    the keywords and skills in the job description. Return a JSON object with one
    key: ''optimized_text''. Job Description: [JOB_DESCRIPTION]. Resume Section: [RESUME_SECTION]'
  score_job_relevance: 'Analyze the following job posting and user profile. Return
    a JSON object with two keys: ''score'' (an integer from 1 to 10 representing relevance)
    and ''reasoning'' (a brief 50-word explanation). Job Posting: [JOB_DESCRIPTION].
    User Profile: [USER_PROFILE]'
proxy:
  enabled: false
  fallback_proxies:
  - host: 47.74.152.29
    port: 8888
    protocol: http
  - host: 103.149.53.120
    port: 80
    protocol: http
  - host: 177.234.217.83
    port: 999
    protocol: http
  - host: 102.132.5.114
    port: 8080
    protocol: http
  - host: 194.233.73.103
    port: 443
    protocol: http
  rotation_interval: 120
  smartproxy:
    country: US
    enabled: false
    endpoint: rotating-residential.smartproxy.com:10000
    password: your_smartproxy_password
    protocol: http
    session_type: sticky
    username: your_smartproxy_username
  validate_on_start: true
search_settings:
  date_posted: Past week
  default_keywords:
  - Solutions Engineer
  - Financial Analyst
  - Analyst
  - Forward Deployed Engineer
  - Deployment Strategist
  - Corporate Finance
  - Business Development
  - Consultant
  default_locations:
  - San Francisco Bay Area
  - New York City
  - Chicago
  - Atlanta
  easy_apply_only: true
  experience_levels:
  - Entry level
  - Internship
  remote_options: Remote
state:
  database_path: ./data/job_applications.db
  storage_type: sqlite
